### ISSUE TITLE
Clarifications and documentation improvements in `iodata.basis`

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#256]
(This was a part of #146.)

There are some points of confusion in the documentation of `iodata.basis` and some names may be confusing. I'll maintain a list of suggestions for improvements below.

- [x] `Shell.nprim`: The "number of primitives" can be interpreted in a few different ways. E.g. `nexp` for number of exponents has less ambiguity. `contraction_length` is too long. See #357
- [ ] `Shell.ncon`: It should be clarified that different contractions within one generalized contraction may, but not must, have different angular momenta. They share the same exponents but have different contraction coefficients. See #359
- [ ] `MolecularBasis.get_segmented`. The terminology of loop "unrolling" in the docstring is confusing. See #373

(Suggestions are welcome.)

Some of the points above imply minor API changes.
