### ISSUE TITLE
Switch to more modern project structure with GitHub Actions

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#313]
This issue replaces some older ones and is used to keep track of several pull requests to reorganize the repository.

I will edit this TODO list to keep it up to date with merged pull requests and suggestions made below:

- [x] Replace `setup.py` by `pyproject.toml`. Fixed in #312. 
    - For some background, see: https://peps.python.org/pep-0518/
    - Version numbers are derived from Git tags with [setuptools-scm](https://pypi.org/project/setuptools-scm/).
    - [x] Also import `__version_tuple__` from `._version` See #315
- [x] Run unit tests and oldest and most recent Python version we'd like to support (3.9 ... 3.12). Fixed in #312
- [x] Rename `master` branch to `main`.
- [x] Add a branch protection rule that forces contributing branches to be made from forks. This prevents the original repository from being overloaded with branches, as is currently the case: https://github.com/theochem/iodata/settings/rules/772871
- [x] Add basic branch protection to the main branch: no force push, no delete. See https://github.com/theochem/iodata/settings/rules/772869
- [x] Add `ruff format` to pre-commit config. See https://docs.astral.sh/ruff/formatter/ (Almost identical to black, faster, will be integrated into `ruff` in the future) See #314 
- [x] Add `ruff` to pre-commit config. (Instead of all other linting tools) See https://docs.astral.sh/ruff/ See #315
- [x] Enable pull request review automation tools: deepsource, sonarcloud, sourcery-ai
- [x] Remove all `importlib_resources` try-except blocks. See #323
- [x] Caputre all warnings in unit tests. This is needed because:
    - Warnings often hint at problems that will become real errors in future version of dependencies. Hence, warnings should result in failed tests, so we certainly fix them before they become a real problem. See #329
    - Warnings can also be the consequence of antipatterns. See #327
    - Some warnings are generated in IOData as user feedback, which should be checked in the tests. See #326 and #328
    - Make pytest exit with an error when there are warnings. See #331
- [x] Update from attr to attrs. See #318 
- [x] Add GitHub actions for PyPI releases. See #317 
    - [x] Initiate a changelog file using the following format: https://keepachangelog.com/en/1.1.0/ See #322
    - [x] Yank `iodata`  releases on PyPI, so there is only the `qc-iodata` package on PyPI
    - [x] Update PyPI classifiers. See #324 
    - [x] Make new alpha release and document how to install it (README and sphinx doxs) See #325
- [x] GitHub Action for documentation build, to replace RTD eventually. See #330
    - More details on why RTD is a problem: #321 
    - [x] Make pull requests fail when docs do not build properly. See #333 
    - [x] Add the `--nitpicky` option to `sphinx-build` in `.github/workflows/sphinx.yaml`, `docs/Makefile` and `docs/make.bat`. Fix all broken references reported by Sphinx with this option enbaled. See #334 
- [x] Update [contributing guidelines](https://github.com/theochem/guidelines/blob/main/contributing.md) or create a new one specifically for this format. A more conventional location for this is the `CONTRIBUTING.md` file in the `.github` repository. We can also add templates for issues and pull requests here. See #332 and #339
- [x] Get coverage analysis back on the rails. See #335
    - Time the unit tests: `pytest --durations=100`
    - Mark the slow ones (e.g. more than  second on my laptop) with `@pytest.mark.slow` as documented here: https://docs.pytest.org/en/6.2.x/mark.html#registering-marks.
    - Document the exclusion of the slow tests in the contributing guide, to help speed up dev iteration.
    - Have separate steps for fast and slow tests in `.github/workflows/pytest.yaml`
    - Enable coverage only for the fast ones.
    - Add a step to `pytest.yaml` to upload coverage artifacts to deepsource, as documented here: https://docs.deepsource.com/docs/analyzers-test-coverage and https://docs.deepsource.com/docs/analyzers-test-coverage#with-github-actions
- [x] Add a code of conduct. See #339
- [ ] Document how to apply the same CI setup to a new repository.
- [x] Archive old branches in a forked repo, to clean up the main repo.

I'll use `iodata` as the first test for this structure, but I've got positive experiences with most steps from other repositories.

Other relevant links not fully covered here:

- #204
- [1.0.0 issues](https://github.com/theochem/iodata/milestone/1)

Relevant older issues and pull requests that were closed and are followed up here:

- #183 
- #189
- #213
- #263
- #299

**Comment by PaulWAyers** [comment]
We store the code-of-conduct, contributing guidelines, and other "universal to QC-Devs repositories" information in this repository:
    https://github.com/theochem/guidelines

In the TL;DR part of the [code of conduct](https://github.com/theochem/guidelines/blob/main/CodeOfConduct.md), we capture Toon's "be nice" 7-character summary but lengthened it to a tweet-sized bite.  
>Treat others with respect, kindness, and empathy; assume they're doing the same. Communicate clearly. Be helpful. Be open. Be nice. If someone says stop; stop.

**Comment by tovrstra** [comment]
@PaulWAyers @FarnazH @evohringer I'm sorry for the Git spam! I just release 1.0.0a3, which you should be able to install with `pip install qc-iodata`. I've yanked old `iodata` releases on PyPI, so `pip install iodata` will give an error message. (There is no way to control the details of the error message, but it is better than letting such a mistake happily install something very old.)

If you send me your PyPI usernames, I can make you co-owner of the `qc-iodata` package on PyPI, which is a nicer way to share permissions than the shared bot account.

**Comment by tovrstra** [comment]
Overview of the slowest tests, to be excluded from coverage analysis:

```
45.03s call     iodata/test/test_molden.py::test_load_dump_consistency[psi4_cuh_cc_pvqz_pure.molden-unnormalized]
23.37s call     iodata/test/test_molden.py::test_load_molden_high_am_orca[cuh]
23.23s call     iodata/test/test_molden.py::test_load_molden_high_am_psi4[cuh]
21.58s call     iodata/test/test_molden.py::test_load_molden_high_am_psi4[zn]
15.96s call     iodata/test/test_molden.py::test_load_molden_high_am_psi4[mn]
12.89s call     iodata/test/test_cp2klog.py::test_carbon_gs_ae_uncontracted
9.97s call     iodata/test/test_molden.py::test_load_molden_nh3_aug_cc_pvqz_cart_psi4
9.78s call     iodata/test/test_cp2klog.py::test_carbon_sc_ae_uncontracted
8.74s call     iodata/test/test_molden.py::test_load_molden_high_am_orca[zn]
6.23s call     iodata/test/test_fchk.py::test_dump_fchk_from_wfn_cah110
6.01s call     iodata/test/test_wfn.py::test_load_dump_consistency_cah110
5.60s call     iodata/test/test_fchk.py::test_dump_fchk_from_molden_nh3
5.26s call     iodata/test/test_fchk.py::test_dump_fchk_from_wfx_cah110
4.27s call     iodata/test/test_molekel.py::test_load_molden_dump_molekel_li2
3.97s call     iodata/test/test_molekel.py::test_load_dump_consistency_li2
3.68s call     iodata/test/test_molden.py::test_load_dump_consistency[li2.molden.input-ORCA]
3.61s call     iodata/test/test_fchk.py::test_dump_fchk_from_molekel_li2
3.55s call     iodata/test/test_molden.py::test_load_molden_li2_orca
2.69s call     iodata/test/test_wfn.py::test_load_one_cah110_hf_sto3g_g09
2.09s call     iodata/test/test_molekel.py::test_load_mkl_li2
1.75s call     iodata/test/test_fchk.py::test_dump_fchk_from_molden_ne
1.64s call     iodata/test/test_wfx.py::test_dump_one_from_molden_nh3
1.32s call     iodata/test/test_molden.py::test_load_molden_nh3_psi4
1.19s call     iodata/test/test_cp2klog.py::test_carbon_gs_pp_uncontracted
1.15s call     iodata/test/test_wfn.py::test_load_dump_consistency_he
1.05s call     iodata/test/test_wfx.py::test_dump_one_from_molden_neon
1.01s call     iodata/test/test_molden.py::test_load_molden_li2_orca_huge_threshold
```

**Comment by tovrstra** [comment]
I am going to close this issue because the only remaining item is now organized in a separate issue: https://github.com/theochem/.github/issues/5
